name: Release

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Release type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
          - prerelease

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run type checking
        run: npm run type-check
        
      - name: Build project
        run: npm run build
        
      - name: Bump version and create tag
        run: |
          npm version ${{ github.event.inputs.release-type }}
          echo "NEW_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
          
      - name: Push changes
        run: |
          git push origin main
          git push origin v${{ env.NEW_VERSION }}
          
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.NEW_VERSION }}
          release_name: Release v${{ env.NEW_VERSION }}
          body: |
            ## Changes in v${{ env.NEW_VERSION }}
            
            Automated release created by GitHub Actions.            ### Installation
            ```bash
            npm install @wolfielabs/shopify-storefront-mcp-server@${{ env.NEW_VERSION }}
            ```
            
            ### Quick Start
            ```bash
            npx -y @wolfielabs/shopify-storefront-mcp-server --storeDomain your-store.myshopify.com
            ```
          draft: false
          prerelease: ${{ contains(github.event.inputs.release-type, 'pre') }}
          
      - name: Publish to NPM
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
